### PR TITLE
Fix unreferenced symbol warnings on OpenWatcom

### LINKED ISSUE #129: Warnings for Watcom 64-atomic inc and dec
It seems like the static uacpi_do_atomic_inc64 and uacpi_do_atomic_dec64 in atomic.h adds code in every module it is referenced in, and also generates two warnings about unused code. It appears this is fixable by adding "inline" to the definitions.

### PR DESCRIPTION
**Pull request by monkuous**
Previously, compiling uACPI on OpenWatcom with a higher-than-default warning  level would generate unreferenced symbol warnings due to dynamic_array.h and helper functions in atomic.h. This PR fixes these by implementing `UACPI_MAYBE_UNUSED` for OpenWatcom and marking the helper functions as inline.

Closes #129.

### CODE REVIEW

File: include/uacpi/platform/compiler.h [hunk 1]
```diff
@@ -65,6 +65,21 @@
     #define UACPI_COMPILER_HAS_BUILTIN_MEMMOVE
     #define UACPI_COMPILER_HAS_BUILTIN_MEMSET
     #define UACPI_COMPILER_HAS_BUILTIN_MEMCMP
+#elif defined(__WATCOMC__)
+    #define uacpi_unlikely(expr) expr
+    #define uacpi_likely(expr) expr
+
+    // The OpenWatcom documentation suggests this should be done using
```
Comment (d-tatianin) [inline include/uacpi/platform/compiler.h:72]: Can you please use
```c
/*
 * <line1>
 * <line2>
 */
 ```
 For multiline comments
